backend:
  name: git-gateway
  repo: bastienrobert/nextstart
  branch: master

media_folder: '/static/uploads'
public_folder: '/static/uploads'

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'data/pages/home.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Introduction, name: introduction, widget: text }
      - label: 'About '
        name: 'about'
        file: 'data/pages/about.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
